### ISSUE TITLE
Missing units of property sets with same name.

### ISSUE THREAD

**Issue by YCamposGes** [Creoox/creoox-ifc2gltfcxconverter#1]
When exporting from IFC to glTF, I have encountered some issues with the JSON generated from the IFC. Some of the property sets contain duplicated values and have lost their original values. Here is a simple Draw.io diagram of the expected output versus the output we received:
![Diagrama sin título drawio](https://github.com/Creoox/creoox-ifc2gltfcxconverter/assets/156998223/8162a78d-d12e-4dee-9961-bd04eff4e881)

The JSON of the properties we received had every property from the IFC listed once, except for any property containing an ID:
![imagen](https://github.com/Creoox/creoox-ifc2gltfcxconverter/assets/156998223/f1bddc95-e82c-4267-b3af-52faf0347a20)
The JSON I needed from the IFC should look something like this:
![imagen](https://github.com/Creoox/creoox-ifc2gltfcxconverter/assets/156998223/d95fb61a-9ea5-4699-8c49-c3e3cbeb2887)

Where properties with the same names but different values are also stored.

Is there any chance we could include a parameter in ifc2gltfcxconverter.json to allow us to retrieve duplicate properties in the JSON?

**Comment by ifcquery** [comment]
Can you share the IFC file?
Should be possible to fix relatively easy

**Comment by ifcquery** [comment]
Can you also please check the "properties": [] 
array of object 
BuildingElementProxy_1, _2, and _3?

The property values are not in sequential order, but the index in  "properties": [] array in each propertySet should point to the correct values in the global "properties": [] array

**Comment by ifcapps** [comment]
This issue is fixed in latest release: https://github.com/Creoox/creoox-ifc2gltfcxconverter/releases/tag/3.0.9
Please check and confirm or report if problems persist.

**Comment by YCamposGes** [comment]
Hi

The issue is fixed, thank you.

**Comment by BIMViewPlus** [comment]
By the way: in which context do you use the application? What kind of business is it? And in a server side workflow, or just manually on a local machine?

**Comment by ifcapps** [comment]
By the way: in which context do you use the application? What kind of business is it? And in a server side workflow, or just manually on a local machine?

**Comment by YCamposGes** [comment]
The application is being tested for our internal use, we expertise on modeling roads, bridges and tunnels. I am on the sofware side of the company making applications for our engineers.
The application is not yet implemented on our workflow, we are testing alternatives on how to save our ifc's data for analysis.
