### ISSUE TITLE
Segmentation fault converting Revit RAC sample IFC 

### ISSUE THREAD

**Issue by xeolabs** [Creoox/creoox-ifc2gltfcxconverter#10]
`ifc2gltfcxconverter` `3_0_19_beta` on Linux throws a seg fault when converting the Revit RAC model.

For reference, the RAC model looks like this when converted with previous ifc2gltf versions and loaded into xeokit:

![Screenshot from 2024-03-14 00-13-33](https://github.com/Creoox/creoox-ifc2gltfcxconverter/assets/83100/fd05f1fb-8368-41a4-9d77-7a75d5124b05)

## To reproduce this issue
`
ifc2gltfcxconverter -i rac.ifc -o model.glb -m model.json -s 25 -t 1000 -e 3 

__ IFC to GLTF converter __ version: 3.0.19 ____________
Loading file "/home/lindsay/xe...s/ifc/Revit/rac.ifc"
Loading file "/home/lindsay/xe...s/ifc/Revit/rac.ifc": 5%
Loading file "/home/lindsay/xe...s/ifc/Revit/rac.ifc": 100%

Segmentation fault (core dumped)
`

IFC file attached:

[rac.zip](https://github.com/Creoox/creoox-ifc2gltfcxconverter/files/14594711/rac.zip)

**Comment by ifcapps** [comment]
Fixed with version 3.0.21
