### ISSUE TITLE
can not run exe ifc2gltfcxconverter on linux and mac

### ISSUE THREAD

**Issue by reno184** [Creoox/creoox-ifc2gltfcxconverter#11]
Hello, I don't understand I download 3.1 release
on linux I change the PATH with .batch_profile, on window I change the PATH on env variables

when I run on mac  (chmod ok)
`ifc2gltfcxconverter -i xxx.ifc -o xxx.glb -m xxx.json`
terminal answer
`cannot execute binary file`

when I run on window 
`ifc2gltfcxconverter.exe -i xxx.ifc -o xxx.glb -m xxx.json`
terminal answer
`cannot read  ifc2gltfcxconverter.json `

does I provide a licenceKey into ifc2gltfcxconverter.json  ?

**Comment by ifcapps** [comment]
There is no Mac version.
The Linux version is tested on Ubuntu.

The Windows version prints this, if the config json file is not found:
"Config file not found: ifc2gltfcxconverter.json"

The converter runs without config file. The config file is only necessary if you have a license key or if you want to change settings.
Do you have already a license key?

**Comment by ifcapps** [comment]
On Windows, you can run it like this:
ifc2gltfcxconverter.exe -i xxx.ifc -o xxx.glb -m xxx.json

You don't need a config json file, it also runs without it.
