### ISSUE TITLE
Release Mac OS version or the source code

### ISSUE THREAD

**Issue by AlexanderMelde** [Creoox/creoox-ifc2gltfcxconverter#15]
Hello Creoox Team,

I tried running the linux version of your converter on an ARM-based apple silicone (M3) mac book, but that unfortunately does not work, I get the "exec format error", which means the executable is not in the correct format to be run on this platform/distribution.
Usually, these errors occur when system libraries etc. used are not available on the host distribution (or available on a different file path).

A typical solution to this problem would be to allow us developers to manually compile the file for the target platform based on the source code (e.g. by using `make`). 

If you wish to not release the source code, I would suggest adding mac os versions to the released binaries.

Kind regards,
Alexander

**Comment by ifcapps** [comment]
Hi Alexander,
our customers run this application mostly server based, and only on Linux and Windows. So at the moment we can not provide a version for Mac OS.
We are working on a WASM version though. That might be interesting for you.
It will be integrated with xeokit, but also standalone IFC to gltf/glb converter, for node.js and as native application like it is now.

Kind Regards,
Fabian

**Comment by AlexanderMelde** [comment]
Hello Fabian,
thank you for the explanation and the answer. 
The WASM version sounds very promising and would allow easier cross-platform development.
Do you already have a timeline for this?
In the meantime, I will propably use Docker for the emulation.
Thank you!

**Comment by AlexanderMelde** [comment]
Hi Diyan,
thank you for this opportunity!
At the moment I have no further questions, but in case something comes up I will get back to it and send you a mail.
The motivation for having mac os (ARM) support was mostly convenience during local development.
Kind regards
Alexander

**Comment by drashevski** [comment]
Hi Alexander,

great and thanks for sharing! We are always happy to assist and receive feedback.

And by the way, viele Grüße aus Karlsruhe! 😄

Diyan
