### ISSUE TITLE
`GLIBC_2.33' not found issues in 4.16

### ISSUE THREAD

**Issue by cT4001** [Creoox/creoox-ifc2gltfcxconverter#16]
![image](https://github.com/user-attachments/assets/61cda851-4b9f-4407-99ea-6bc95a7c5c0c)

As you could see in the screenshot, on Debian we got `GLIBC_2.33' not found issues. I could remember from an 2.x version, that there were similar issues, where you at the end provided a build that include the linked libraries… 

(the previous 4.4 beta was running fine on the same server)

Could you help us?

**Comment by ifcapps** [comment]
I created a ticket here to further investigate: https://creoox.atlassian.net/browse/XCD-160
