### ISSUE TITLE
Duplicate metaobjects in split output

### ISSUE THREAD

**Issue by xeolabs** [Creoox/creoox-ifc2gltfcxconverter#3]
Just tracking this issue we discussed earlier: when converting an IFC and splitting it into multiple glTF+JSON files, the JSON files contain duplicates of the metaobjects. Would be ideal to ensure no duplicates between the JSONs.

**Comment by ifcquery** [comment]
To ensure a valid tree, some objects like IfcSite or IfcCurtainWall have to be duplicated. Not the meshes, only the JSON object.
The overhead is very low, shouldn't be a problem

**Comment by xeolabs** [comment]
Yeah duplicated parent elements make sense, but wasn't there a situation where multiple JSON files each contained the full set of duplicated metaobjects? If not then I misunderstood and we can close this issue.

**Comment by ifcquery** [comment]
I am not aware of such a case.
In my tests, the sum of 5 split JSON files was just a few kBytes above the unsplit file, less than 1 %

**Comment by xeolabs** [comment]
Ah OK I misunderstood - closing this issue then.
