### ISSUE TITLE
get only metadata and skipping xkt output?

### ISSUE THREAD

**Issue by cT4001** [Creoox/creoox-ifc2gltfcxconverter#4]
Hi together,

guess there is no way (until now) to skipt xkt out and only output the metdata json, right?
background: we converted our dataset (with > 3000 ifc files) already to xkt, but sadly discarded the metadata jsons... Now we need to add the metadata and do not want to covert everything again..

**Comment by ifcquery** [comment]
Hmm, good question. 

If you access the metadata directly from the JSON file, then you need to run only the ifc2gltf converter:
ifc2gltfcxconverter -o fileName.gltf -m metadata.json

Conversion to xkt is not necessary in that case.

If you access metadata from the xkt file (compressed), then you have to run the conversion from (gltf+json) -> xkt.

**Comment by ifcapps** [comment]
The converter has been updated several times meanwhile, so it makes sense to run the conversion for all files again, with geometry + metadata.
Theoretically it is possible to exclude geometry from the conversion process, converting only meta data. But that would add complexity to the application, so not planned at the moment.
