### ISSUE TITLE
Feature request: option to center a model's coordinates during conversion

### ISSUE THREAD

**Issue by xeolabs** [Creoox/creoox-ifc2gltfcxconverter#5]
Can we add an option to center a model during conversion? It would be fine to insert an extra root `node` into the glTF `scene` hierarchy 

If we could even tag that `node` with a special reserved `name` value (eg. "ifc2gltf-centering"), then `xeokit-convert`'s `convert2xkt` tool could have the option to ignore that `node`, to not apply the centering during glTF->XKT conversion.

**Comment by ifcquery** [comment]
Yes, makes sense and not a big deal to add.
Will put the option "centerModelAtOrigin" in the input config file.

**Comment by ifcapps** [comment]
Implemented meanwhile
