### ISSUE TITLE
Some MetaModel PropertySets don't have 'properties' attributes

### ISSUE THREAD

**Issue by xeolabs** [Creoox/creoox-ifc2gltfcxconverter#8]
`ifc2gltfcxconverter` `3_0_19_beta` on Linux creates in the metamodel JSON some PropertySets that do not have `properties` attributes.

 This creates a bug in xeokit-sdk when loading the metamodels, which assumes that the `properties` array exists on each PropertySet, ie. here:
 
![Screenshot from 2024-03-13 15-46-00](https://github.com/Creoox/creoox-ifc2gltfcxconverter/assets/83100/8d23e048-e925-47bd-865b-b8f7be60156a)

I can share some private models via Jira to reproduce this issue if needed.

For now, I'll make xeokit-sdk and xeokit-bim-viewer ignore these PropertySets.

**Comment by ifcapps** [comment]
Do you have a mininum example with as few objects as possible that causes the crash in the converter on Linux?

In general it is difficult to debug a C++ app on Linux, but I will try.

**Comment by ifcapps** [comment]
Should be fixed with version 3.0.21.
Please re-open if issue persists.
