### ISSUE TITLE
MetaModel JSON "metaObjects" array contains multiple empty objects

### ISSUE THREAD

**Issue by xeolabs** [Creoox/creoox-ifc2gltfcxconverter#9]
`ifc2gltfcxconverter` `3_0_19_beta` on Linux creates several empty objects at the end of the `metaObjects` array in the metamodel JSON.

This causes `xeokit-sdk` `TreeViewPlugin` to create multiple excess tree roots, which is its correct behaviour (it uses defaults for the missing attributes on those empty objects, which it interprets as default MetaObjects).

![Screenshot from 2024-03-13 22-55-23](https://github.com/Creoox/creoox-ifc2gltfcxconverter/assets/83100/ace6cac3-cb31-458e-8710-0ba231fd6ce8)

Screenshot below shows a snippet of the metamodel JSON:

![Screenshot from 2024-03-13 23-00-22](https://github.com/Creoox/creoox-ifc2gltfcxconverter/assets/83100/458f0024-08b7-426f-9615-dec64116c96f)

## To reproduce

`ifc2gltfcxconverter -i eed01637-d47a-46a4-8707-0438319a5cbd_AR-Demo_Sample_Building_01.ifc -o model.glb -m model.json -s 25 -t 1000 -e 3 >> log.txt` 

IFC model is attached.

[eed01637-d47a-46a4-8707-0438319a5cbd_AR-Demo_Sample_Building_01.zip](https://github.com/Creoox/creoox-ifc2gltfcxconverter/files/14594335/eed01637-d47a-46a4-8707-0438319a5cbd_AR-Demo_Sample_Building_01.zip)

**Comment by ifcapps** [comment]
Fixed with version 3.0.21
